### ISSUE TITLE
Pages Deployment zeigt 404

### ISSUE THREAD

**Issue by almereyda** [berlin/lod-organigram#2]
Beim Aufruf von https://berlin.github.io/lod-organigram/ erscheint gegenwärtig ein 404 Page not found Fehler.

Dadurch wird das RDF Vokabularium undereferenzierbar, bspw. genutzt beim RDF Export auf https://organigramme.odis-berlin.de/

Vielleicht ist die Verwendung einer https://w3id.org/ auch eine Möglichkeit dem zu begegnen.

**Comment by almereyda** [comment]
@knudmoeller Knud, ich sehe das Repositorium ist ein Fork eines Templates von dir.

Ist dies ein wiederkehrender Fall, der auch in anderen Forks auftritt? Ich konnte den Fehler nicht richtig eingrenzen, weshalb ich es hier offen stehen gelassen habe.

Vielleicht weißt du ja Abhilfe oder hast eine Idee, wer sich hierzu ansprechen ließe?

**Comment by knudmoeller** [comment]
Hi @almereyda , danke für den Hinweis! Stimmt, lod-organigram basiert auf https://github.com/berlinonline/lod-sg, was als Template für die Veröffentlichung von RDF mit gh-pages dienen soll. lod-sg ist aber sehr fummelig zu konfigurieren, und hier stimmt irgendetwas mit der Konfiguration nicht. Ich habe schon länger auf der TODO-Liste, mir das anzuschauen – jetzt unternehme ich noch mal einen Versuch!

**Comment by almereyda** [comment]
Vielen Dank Knud.

**Comment by knudmoeller** [comment]
Das Problem (Setup der Ruby-Dependency in der Github-CI) wurde behoben und die Organigramm-LOD sind jetzt wieder online!
